
---

### `config/settings.yaml` (пример настроек)

```yaml
interval_seconds: 3

ranks: ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']
suits: ['S', 'H', 'D', 'C']  # Spades, Hearts, Diamonds, Clubs
